config/routes.rb
Rails.application.routes.draw do
  root   'events#index'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  post   '/attend',    to: 'events#add_attendee'
  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users, only:[:new, :create, :show]
  resources :events, only:[:new, :create, :show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }

  has_many :event_listings, :foreign_key => 'attended_event_id'
  has_many :attendees, :through => :event_listings
  belongs_to :creator, :class_name => 'User'
end

app/models/event_listing.rb
class EventListing < ApplicationRecord
  belongs_to :attendee, :class_name => 'User'
  belongs_to :attended_event, :class_name => 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_listings, :foreign_key => :attendee_id
  has_many :attended_events, :through => :event_listings
  has_many :created_events, :foreign_key => :creator_id, :class_name => 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  def create
    @event = current_user.created_events.build(event_params)
    @event.date = @event.date.to_time
    @event.save
    flash[:success] = 'Event Created'
    redirect_to root_url
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def new
    if logged_in?
      @event = current_user.created_events.build
    else
      flash[:danger] = 'Please login first'
      redirect_to login_path
    end
  end

  def index
    @events = Event.all
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      flash[:success] = 'Logged In'
      redirect_to user
    else
      flash[:danger] = 'No email found'
      redirect_to login_path
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = 'Logged Out'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    log_in(@user)
    flash[:success] = 'User created'
    redirect_to @user
  end

  def show
    @user = User.find_by(id: params[:id])
    @upcoming_events = upcoming_events(current_user)
    @previous_events = previous_events(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Private Events"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def add_attendee
    event = Event.find_by(id: params[:event])
    user = User.find_by(id: params[:user])
    event.attendees << user
    flash[:success] = "Attended #{event.title}"
    redirect_to root_url
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def upcoming_events(user)
    events = user.attended_events.where("date > ?", Time.now)
  end

  def previous_events(user)
    events = user.attended_events.where("date < ?", Time.now)
  end
end

app/views/events/_past_events.html.erb
<div class="col-md-4">
<h3> Past Events </h3>
  <% @events.past.each do |e| %>
   <p><%= link_to e.title, e %></p>
    <p><%= e.description %></p>
    <p><%= e.date %></p>
    <p><%= "Created By: #{e.creator.name}" %>
    <p> Attended By: 
      <% e.attendees.each do |att| %>
        <%= link_to att.name, att %>
      <% end %>
    </p>
    <hr>
  <% end %>
</div>

app/views/events/_upcoming_events.html.erb
<div class="col-md-4">
<h3> Upcoming Events </h3>
  <% @events.upcoming.each do |e| %>
    <p><%= link_to e.title, e %></p>
    <p><%= e.description %></p>
    <p><%= e.date %></p>
    <p><%= "Created By: #{e.creator.name}" %>
    <p> Attended By: 
      <% e.attendees.each do |att| %>
        <%= link_to att.name, att %>
      <% end %>
    </p>
    <hr>
  <% end %>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<% provide(:title, "All Events") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        All Events
      </h1>
      <h2><%= link_to "Create New Event", new_event_path %></h3>
    </section>
  </aside>
  <%= render 'past_events' %>
  <%= render 'upcoming_events' %>
</div>

app/views/events/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create New Event') %>
<h1>Create new event</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.datetime_local_field :date, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<div class="row">
  <div class="col-md-8">
    <p><%= "Event Name: #{@event.title}" %></p>
    <p><%= "Description: #{@event.description}" %></p>
    <p><%= "Event Date: #{@event.date}" %></p>
    <p> Attendees:
    <% @event.attendees.each do |att| %>
       <%= link_to att.name, att %>
       /
    <% end %>
    <%= link_to "Attend this event", attend_path(:event => @event, :user => current_user), method: :post %>
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "private events", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Logged in as #{current_user.name}", current_user %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_previous_events.html.erb
<div class="col-md-4">
  <h3> Previous Events </h2>
  <% unless @previous_events.nil? %>
    <% @previous_events.each do |e| %>
      <p><%= link_to e.title, e %></p>
      <p><%= e.description %></p>
      <p><%= e.date %></p>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/users/_upcoming_events.html.erb
<div class="col-md-4">
  <h3> Attending Events </h3>
  <% @upcoming_events.each do |e| %>
    <p><%= link_to e.title, e %></p>
    <p><%= e.description %></p>
    <p><%= e.date %></p>
    <hr>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', url: signup_path %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, current_user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= current_user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  </div>
</div>